main – Linreg
main Program
12 statements
Source File
Uses
allRoutines
Calls
Contents
None
Call graph
main calls convertkappa, calcsums, calcab, parseinput, printresults, deallocall, calcvariance, calcmeanslope